MD C:\Users\yangwang\Desktop\Cupoy-NLP\Day004
MD C:\Users\yangwang\Desktop\Cupoy-NLP\Day005
MD C:\Users\yangwang\Desktop\Cupoy-NLP\Day006
MD C:\Users\yangwang\Desktop\Cupoy-NLP\Day007
MD C:\Users\yangwang\Desktop\Cupoy-NLP\Day008
MD C:\Users\yangwang\Desktop\Cupoy-NLP\Day009
MD C:\Users\yangwang\Desktop\Cupoy-NLP\Day010
MD C:\Users\yangwang\Desktop\Cupoy-NLP\Day011
MD C:\Users\yangwang\Desktop\Cupoy-NLP\Day012
MD C:\Users\yangwang\Desktop\Cupoy-NLP\Day013
MD C:\Users\yangwang\Desktop\Cupoy-NLP\Day014
MD C:\Users\yangwang\Desktop\Cupoy-NLP\Day015
MD C:\Users\yangwang\Desktop\Cupoy-NLP\Day016
MD C:\Users\yangwang\Desktop\Cupoy-NLP\Day017
MD C:\Users\yangwang\Desktop\Cupoy-NLP\Day018
MD C:\Users\yangwang\Desktop\Cupoy-NLP\Day019
MD C:\Users\yangwang\Desktop\Cupoy-NLP\Day020
MD C:\Users\yangwang\Desktop\Cupoy-NLP\Day021
MD C:\Users\yangwang\Desktop\Cupoy-NLP\Day022
MD C:\Users\yangwang\Desktop\Cupoy-NLP\Day023
MD C:\Users\yangwang\Desktop\Cupoy-NLP\Day024
MD C:\Users\yangwang\Desktop\Cupoy-NLP\Day025
MD C:\Users\yangwang\Desktop\Cupoy-NLP\Day026
MD C:\Users\yangwang\Desktop\Cupoy-NLP\Day027
MD C:\Users\yangwang\Desktop\Cupoy-NLP\Day028